ATTime/Controllers/StudentViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATTime.Models.LoginViewModels;
using Microsoft.EntityFrameworkCore;
using ATTime.Models;

namespace ATTime.Controllers
{
    public class StudentViewController : Controller
    {
        public ActionResult Index()
        {
            //Her fanger vi alle sessions som indeholder information for den bruger som er logget ind:
            var context = new ATTime_DBContext();
            var currentid = ((int)Session["UserId"]);
            var currentrole = ((string)Session["UserRole"]);
            var school = ((int)Session["School"]);
            var schoolid = context.Students.Where(s => s.StudentId == currentid).Single().SchoolId;
            var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;
            var schoolname = context.Schools.Where(s => s.SchoolId == schoolid).Single().SchoolName;
            int? team = context.TeamStudents.Where(s => s.StudentId == currentid).Single().TeamId;
            ViewData["id"] = currentid;
            ViewData["Role"] = currentrole;
            ViewData["Schoolname"] = schoolname;
            ViewData["Logo"] = schoollogo;
            ViewData["team"] = team;

            //Tilføj alt koden her
           var today = DateTime.Now.ToString("dd-MM-yyyy");
            var today_id = context.Calenders.Where(s => s.CalenderName == today).Single().CalenderId;
            var today_course = context.CourseCalenders
                 .Where(s => s.CalenderId == today_id)
                 .Where(s => s.TeamId == team)
                 .Include(s => s.Course)
                 .Single().Course.CourseName;
             var today_course_id = context.CourseCalenders
               .Where(s => s.CalenderId == today_id)
               .Where(s => s.TeamId == team)
               .Single().CourseId;
             ViewData["TC"] = today_course;
             ViewData["CID"] = today_course_id;

            if(context.AttendanceCourseStudents
               .Where(s => s.StudentId == currentid)
               .Where(s => s.TeamId == team)
               .Where(s => s.CalenderId == today_id)
               .Count() == 0)
            {
                ViewBag.att = 1;
            }
            else
            {
                int? attendance = context.AttendanceCourseStudents
                               .Where(s => s.StudentId == currentid)
                               .Where(s => s.TeamId == team)
                               .Where(s => s.CalenderId == today_id)
                               .Single().AttendanceId;
                ViewBag.att = attendance;
            }

            var student_courses = context.CourseStudents
                 .Where(s => s.StudentId == currentid)
                 .ToList();
             ViewBag.Student_courses = student_courses;

             var calender = context.CourseCalenders
                 .Where(s => s.TeamId == team)
                 .ToList();
            ViewBag.calender = calender; 
       
            //Sakffer routen for en bruger
            if (currentrole == "Student" && currentid != 0)
            {
                return View();
            }
            else
            {
                string url = LoginCheckViewModel.check(currentid, currentrole);
                return RedirectToAction("Index", url);
            }
        }

        public ActionResult attend(string code_for_torday)
        {
            //Her fanger vi alle sessions som indeholder information for den bruger som er logget ind:
            var context = new ATTime_DBContext();
            var currentid = ((int)Session["UserId"]);
            var currentrole = ((string)Session["UserRole"]);
            var school = ((int)Session["School"]);
            var schoolid = context.Students.Where(s => s.StudentId == currentid).Single().SchoolId;
            var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;
            var schoolname = context.Schools.Where(s => s.SchoolId == schoolid).Single().SchoolName;
            int? team = context.TeamStudents.Where(s => s.StudentId == currentid).Single().TeamId;
            ViewData["id"] = currentid;
            ViewData["Role"] = currentrole;
            ViewData["Schoolname"] = schoolname;
            ViewData["Logo"] = schoollogo;
            ViewData["team"] = team;

            //Koden er gengivet fra index af, så alt det samme information kommer med igen, når man trykker tilmeld.
            var today = DateTime.Now.ToString("dd/MM/yyyy");
            var today_id = context.Calenders.Where(s => s.CalenderName == today).Single().CalenderId;
            string today_course = context.CourseCalenders
                .Where(s => s.CalenderId == today_id)
                .Where(s => s.TeamId == team)
                .Include(s => s.Course)
                .Single().Course.CourseName;
            var today_course_id = context.CourseCalenders
              .Where(s => s.CalenderId == today_id)
              .Where(s => s.TeamId == team)
              .Include(s => s.Course)
              .Single().Course.CourseId;
            ViewData["TC"] = today_course;
            ViewData["CID"] = today_course_id;

            var attendance = context.AttendanceCourseStudents
                .Where(s => s.StudentId == currentid && s.TeamId == team && s.CalenderId == today_id)
                .FirstOrDefault().AttendanceId;
            ViewBag.att = attendance;

            var student_courses = context.CourseStudents
                .Where(s => s.StudentId == currentid)
                .ToList();
            ViewBag.Student_courses = student_courses;

            var calender = context.CourseCalenders
                .Where(s => s.TeamId == team)
                .ToList();
            ViewBag.calender = calender;

            //Koden som denne action skal bruge
            var acsID = context.AttendanceCourseStudents
                .Where(s => s.CalenderId == today_id)
                .Where(d => d.StudentId == currentid)
                .FirstOrDefault().AttendanceCourseStudentId;
            var check_code = context.CourseCodes
              .Where(s => s.CalenderId == today_id)
              .Single().Code;
            if (code_for_torday == check_code)
            {
                using (context)
                {
                    var std = context.AttendanceCourseStudents
                        .Where(s => s.AttendanceCourseStudentId == acsID)
                        .FirstOrDefault();
                    std.AttendanceId = 2;
                    context.SaveChanges();
                }
                ViewBag.msg = "You have attended the course.";
            }
            else
            {
                ViewBag.msg = "You didn't use the right code for todays course.";
            }

            //Sakffer routen for en bruger
            if (currentrole == "Student" && currentid != 0)
            {
                return View("index");
            }
            else
            {
                string url = LoginCheckViewModel.check(currentid, currentrole);
                return RedirectToAction("Index", url);
            }
        }

        public ActionResult procentage()
        {
            //Her fanger vi alle sessions som indeholder information for den bruger som er logget ind:
            var context = new ATTime_DBContext();
            var currentid = ((int)Session["UserId"]);
            var currentrole = ((string)Session["UserRole"]);
            var school = ((int)Session["School"]);
            var schoolid = context.Students.Where(s => s.StudentId == currentid).Single().SchoolId;
            var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;
            var schoolname = context.Schools.Where(s => s.SchoolId == schoolid).Single().SchoolName;
            int? team = context.TeamStudents.Where(s => s.StudentId == currentid).Single().TeamId;
            ViewData["id"] = currentid;
            ViewData["Role"] = currentrole;
            ViewData["Schoolname"] = schoolname;
            ViewData["Logo"] = schoollogo;
            ViewData["team"] = team;

            //Tilføj alt koden her
            var courses = context.CourseStudents
                .Where(s => s.StudentId == currentid)
                .Include(s => s.Course)
                .ToList();

            ViewBag.course = courses;

            //Sakffer routen for en bruger
            if (currentrole == "Student" && currentid != 0)
            {
                return View();
            }
            else
            {
                string url = LoginCheckViewModel.check(currentid, currentrole);
                return RedirectToAction("Index", url);
            }
        }
    }
}

ATTime/Views/StudentView/Index.cshtml
@using ATTime.Models.LoginViewModels;
@using ATTime.Models.ViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Student.cshtml";
}
@if (ViewBag.att == 2)
 {
    <h2>You have attended todays course.</h2>
 }
else
{
    if (Studencount.count_courses(((int)ViewData["id"]), ((int)ViewData["CID"])) > 0)
    {
        if (((int)ViewData["CID"]) == 1)
        {
            <h2>You have study day today.</h2>
        }
        else
        {
            <h2>Check in</h2>
            <h3>Todays course is @ViewData["TC"]</h3>

            using (Html.BeginForm("attend", "StudentView", FormMethod.Post))
            {
                <input type="text" name="code_for_torday" />
                <button type="submit" class="btn btn-default m-1 p-1 btn-success modalBtn haps">Check in</button>
            }
        }
    }
    else if (((int)ViewData["CID"]) == 1)
    {
        <h2>You have study day today.</h2>
    }
    else
    {

        <h2>Check in</h2>
        <h3>Todays course is @ViewData["TC"]</h3>

        using (Html.BeginForm("attend", "StudentView", FormMethod.Post))
        {
            <input type="text" name="code_for_torday" />
            <button type="submit" class="btn btn-default m-1 p-1 btn-success modalBtn">Check in</button>
        }

        <h3>You are currently not on a Team</h3>

    }
}

ATTime/Views/StudentView/procentage.cshtml
@using ATTime.Models
@using ATTime.Models.ViewModel
@{
    ViewBag.Title = "procentage";
    Layout = "~/Views/Shared/_Layout_Student.cshtml";
}
<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<h2>Absence</h2>

<div class="row">
    @foreach (CourseStudent c in ViewBag.course)
    {
    <div class="col-3">
        <div id="@c.Course.CourseName"></div>
        <script type="text/javascript">
            // Load google charts
            google.charts.load('current', { 'packages': ['corechart'] });
            google.charts.setOnLoadCallback(drawChart);

            // Draw the chart and set the chart values
            function drawChart() {
                var data = google.visualization.arrayToDataTable([
                    ['Absence', 'Procentage for absence'],
                    ['Absence', @Studencount.total_absent_course(c.StudentId, c.CourseId) ],
                    ['Attendance', 100 - @Studencount.total_absent_course(c.StudentId, c.CourseId)],
                ]);

                // Optional; add a title and set the width and height of the chart
                var options = { 'title': '@c.Course.CourseName absences', 'width': 80%, 'height': 'auto' };

                // Display the chart inside the <div> element with id="piechart"
                var chart = new google.visualization.PieChart(document.getElementById('@c.Course.CourseName'));
                chart.draw(data, options);
            }
        </script>
    </div>
    }
</div>