ATTime/Models/Calender.cs
using System;
using System.Collections.Generic;

namespace ATTime.Models
{
    public partial class Calender
    {
        public Calender()
        {
            AttendanceCourseStudent = new HashSet<AttendanceCourseStudent>();
            CourseCalender = new HashSet<CourseCalender>();
            CourseCode = new HashSet<CourseCode>();
        }

        public int CalenderId { get; set; }
        public string CalenderName { get; set; }

        public ICollection<AttendanceCourseStudent> AttendanceCourseStudent { get; set; }
        public ICollection<CourseCalender> CourseCalender { get; set; }
        public ICollection<CourseCode> CourseCode { get; set; }
    }
}

ATTime/Models/Student.cs
using System;
using System.Collections.Generic;

namespace ATTime.Models
{
    public partial class Student
    {
        public Student()
        {
            AttendanceCourseStudent = new HashSet<AttendanceCourseStudent>();
            CourseStudent = new HashSet<CourseStudent>();
            TeamStudent = new HashSet<TeamStudent>();
        }

        public int StudentId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Username { get; set; }
        public string Psw { get; set; }
        public int? SchoolId { get; set; }

        public School School { get; set; }
        public ICollection<AttendanceCourseStudent> AttendanceCourseStudent { get; set; }
        public ICollection<CourseStudent> CourseStudent { get; set; }
        public ICollection<TeamStudent> TeamStudent { get; set; }
    }
}

ATTime/Controllers/TeacherViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ATTime.Models.LoginViewModels;
using Microsoft.EntityFrameworkCore;
using ATTime.Models;


namespace ATTime.Controllers
{
    public class TeacherViewController : Controller
    {
        public ActionResult Index()
        {
            if (((int)Session["UserId"]) == 0)
            {
                return RedirectToAction("Index", "Login");
            }
            else
            {
                //Her fanger vi alle sessions som indeholder information for den bruger som er logget ind:
                var context = new ATTime_DBContext();
                var currentid = ((int)Session["UserId"]);
                var currentrole = ((string)Session["UserRole"]);
                var school = ((int)Session["School"]);
                var schoolid = context.Operators.Where(s => s.OperatorId == currentid).Single().SchoolId;
                var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;
                var schoolname = context.Schools.Where(s => s.SchoolId == schoolid).Single().SchoolName;
                ViewData["id"] = currentid;
                ViewData["Role"] = currentrole;
                ViewData["Schoolname"] = schoolname;
                ViewData["Logo"] = schoollogo;

                //Tilføj koden her:
                var teams_operator = context.TeamOperators
                .Where(s => s.OperatorId == currentid)
                .Include(s => s.Team)
                .ToList();

                ViewBag.TO = teams_operator;


                //Sakffer routen for en bruger
                if (currentrole == "Teacher" && currentid != 0)
                {
                    return View();
                }
                else
                {
                    string url = LoginCheckViewModel.check(currentid, currentrole);
                    return RedirectToAction("Index", url);
                }
            }
        }

        public ActionResult AddCourse(int Courseid, int calendercourseid, int teamid)
        {
            //Informationer
            var context = new ATTime_DBContext();
            var currentid = ((int)Session["UserId"]);
            var currentrole = ((string)Session["UserRole"]);
            var school = ((int)Session["School"]);
            var schoolid = context.Operators.Where(s => s.OperatorId == currentid).Single().SchoolId;
            var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;
            var schoolname = context.Schools.Where(s => s.SchoolId == schoolid).Single().SchoolName;
            ViewData["id"] = currentid;
            ViewData["Role"] = currentrole;
            ViewData["Schoolname"] = schoolname;
            ViewData["Logo"] = schoollogo;
            ViewData["team"] = teamid;

            //Dage i ugen 
            List<Days> dage = new List<Days>();
            for (int i = 0; i < 7; i++)
            {
                dage.Add(new Days() { dag = DateTime.Now.AddDays(i).ToString("dddd") });
            }
            ViewBag.dage = dage;

            //Koden fra calender
            var start_date = DateTime.Now.ToString("dd-MM-yyyy");
            var startid = context.Calenders.Where(s => s.CalenderName == start_date).Single().CalenderId;
            var teams_calender = context.CourseCalenders
                           .Where(s => s.TeamId == teamid)
                           .Where(s => s.CalenderId >= startid)
                           .Include(s => s.Course)
                           .Include(s => s.Calender)
                            .OrderBy(s => s.CalenderId)
                           .ToList();

            var course_operator = context.CourseOperators
                   .Where(s => s.OperatorId == currentid)
                   .Include(s => s.Course)
                   .ToList();

            ViewBag.TO = teams_calender;
            ViewBag.CO = course_operator;
            var tid = context.Calenders.Where(s => s.CalenderName == start_date).Single().CalenderId;
            ViewBag.today = tid;

            //Selven koden til funktionen
            var today = DateTime.Now.ToString("dd/MM/yyyy");
            var today_id = context.Calenders.Where(s => s.CalenderName == today).Single().CalenderId;

            //Skaffer en random kode, som kan bruges til at bekræfte man er der på dagen: 
            var allChar = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
            var random = new Random();
            var resultToken = new string(
               Enumerable.Repeat(allChar, 5)
               .Select(token => token[random.Next(token.Length)]).ToArray());

            string authToken = resultToken.ToString();

            using (context)
            {
                var calender = context.CourseCalenders.Where(s => s.CourseCalenderId == calendercourseid).Single().CalenderId;
                var students = context.TeamStudents
                    .Where(s => s.TeamId == teamid)
                    .ToList();
                //opdateret faget i coursecalender for teamet
                var addcourse = context.CourseCalenders
                        .Where(s => s.CourseCalenderId == calendercourseid)
                        .Where(s => s.TeamId == teamid)
                        .FirstOrDefault();
                addcourse.CourseId = Courseid;

                //Opdatere for hver studerende, at de ikke har været der endnu
                foreach (TeamStudent s in students)
                {
                    var check = context.AttendanceCourseStudents.Where(d => d.CalenderId == calender).Where(h => h.StudentId == s.StudentId).Count();
                    if (check > 0)
                    {

                    }
                    else
                    {
                        context.AttendanceCourseStudents.Add(new AttendanceCourseStudent() { AttendanceId = 1, CourseId = Courseid, StudentId = s.StudentId, TeamId = teamid, CalenderId = calender });
                    }
                }


                //tilføjer en kode til dagen, så man kan tjekke ind:
                var calender_day = context.CourseCalenders
                    .Where(s => s.CourseCalenderId == calendercourseid)
                    .Single().CalenderId;
                var code = new CourseCode()
                {
                    Code = authToken,
                    CalenderId = calender_day,
                    TeamId = teamid

                };
                context.CourseCodes.Add(code);
                context.SaveChanges();
            }
            //Return
            return View("calender");
        }

        public ActionResult calender(int teamid)
        {
            //Her fanger vi alle sessions som indeholder information for den bruger som er logget ind:
            var context = new ATTime_DBContext();
            var currentid = ((int)Session["UserId"]);
            var currentrole = ((string)Session["UserRole"]);
            var school = ((int)Session["School"]);
            var schoolid = context.Operators.Where(s => s.OperatorId == currentid).Single().SchoolId;
            var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;
            var schoolname = context.Schools.Where(s => s.SchoolId == schoolid).Single().SchoolName;
            ViewData["id"] = currentid;
            ViewData["Role"] = currentrole;
            ViewData["Schoolname"] = schoolname;
            ViewData["Logo"] = schoollogo;
            ViewData["team"] = teamid;
            var teamname = context.Teams.Where(s => s.TeamId == teamid).FirstOrDefault().TeamName;
            ViewBag.teamname = teamname;

            //Dage i ugen 
            List<Days> dage = new List<Days>();
            for (int i = 0; i < 7; i++)
            {
                dage.Add(new Days() { dag = DateTime.Now.AddDays(i).ToString("dddd") });
            }
            ViewBag.dage = dage;

            //Tilføj koden her:
            var start_date = DateTime.Now.ToString("dd-MM-yyyy");
            var startid = context.Calenders.Where(s => s.CalenderName == start_date).Single().CalenderId;
            var teams_calender = context.CourseCalenders
                           .Where(s => s.TeamId == teamid)
                           .Where(s => s.CalenderId >= startid)
                           .Include(s => s.Course)
                           .Include(s => s.Calender)
                           .OrderBy(s => s.CalenderId)
                           .ToList();

          var course_operator = context.CourseOperators
                 .Where(s => s.OperatorId == currentid)
                 .Include(s => s.Course)
                 .ToList();

          ViewBag.TO = teams_calender;
          ViewBag.CO = course_operator;
            var tid = context.Calenders.Where(s => s.CalenderName == start_date).Single().CalenderId;
            ViewBag.today = tid;

            //Sakffer routen for en bruger
            if (currentrole == "Teacher" && currentid != 0)
            {
                return View();
            }
            else
            {
                string url = LoginCheckViewModel.check(currentid, currentrole);
                return RedirectToAction("Index", url);
            }

        }

        public ActionResult between(int teamid, DateTime start, DateTime end)
        {
            //Her fanger vi alle sessions som indeholder information for den bruger som er logget ind:
            var context = new ATTime_DBContext();
            var currentid = ((int)Session["UserId"]);
            var currentrole = ((string)Session["UserRole"]);
            var school = ((int)Session["School"]);
            var schoolid = context.Operators.Where(s => s.OperatorId == currentid).Single().SchoolId;
            var schoollogo = context.Schools.Where(s => s.SchoolId == schoolid).Single().Logo;

ATTime/Views/TeacherView/Index.cshtml
@using ATTime.Models.LoginViewModels;
@using ATTime.Models;
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_Teacher.cshtml";
}
<h2 class="text-lg-left">Teams</h2>
<div class="row">
    @foreach (TeamOperator team in ViewBag.TO)
    {
        @Html.Partial("_team_teacher", team)
    }
</div>

ATTime/Views/TeacherView/attend.cshtml
@model ATTime.Models.AttendanceCourseStudent
@using ATTime.Models.ViewModel
@using ATTime.Models

@functions{
    public int today_id()
    {
        ATTime_DBContext context = new ATTime_DBContext();
        var today = DateTime.Now.ToString("dd/MM/yyyy");
        var today_id = context.Calenders.Where(s => s.CalenderName == today).Single().CalenderId;
        return today_id;
    }
}

<div>
    <h3 style="width: 90%; float:left;">@ViewBag.team, @ViewBag.course d. @ViewBag.date</h3>
    <p class="close" style="width:9%;">X</p>
    <h4>Code: @ViewBag.code</h4>
    @foreach (ATTime.Models.AttendanceCourseStudent a in ViewBag.ATT)
    {
        if (Studencount.count_courses(((int)a.StudentId), ((int)a.CourseId)) > 0)
        {
            <div class="row">
                <div class="col-6">@a.Student.FirstName @a.Student.LastName</div>
                <div class="col-6">
                    @if (a.AttendanceId == 1 && a.CalenderId >= today_id())
                    {
                        <div class="row">
                            <div class="col-3">
                                <div class="pending"></div>
                            </div>
                            <div class="col-9">
                                <p>Pending</p>
                            </div>
                        </div>
                    }
                    else if (a.AttendanceId == 1)
                    {
                        <div class="row">
                            <div class="col-3">
                                <div class="didn"></div>
                            </div>
                            <div class="col-9">
                                <p>Didn't Attend</p>
                            </div>
                        </div>
                    }
                    else
                    {
                        <div class="row">
                            <div class="col-3">
                                <div class="did"></div>
                            </div>
                            <div class="col-9">
                                <p>Attended</p>
                            </div>
                        </div>
                    }
                </div>
            </div>
        }
    }
</div>
<script>
    $(".close").click(function () {
        $("#data").empty();
        $("#data").removeClass("show");
    });
</script>

ATTime/Views/TeacherView/calender.cshtml
@using ATTime.Models.LoginViewModels;
@using ATTime.Models;
@{
    Layout = "~/Views/Shared/_Layout_Teacher_two.cshtml";
}
<div id="data" class="data"></div>
<div class="row att_row">
    <h2 class="float-left col-3 mb-0 text-lg-left p-0 mt-1">@ViewBag.teamname</h2>
    <div class="float-lg-right">
        <p>@ViewBag.msg</p>
        @using (Html.BeginForm("between", "TeacherView", FormMethod.Post))
        {
            <input type="hidden" value="@ViewData["team"]" name="teamid" />
            <label>Start date</label>
            <input type="date" name="start" id="Date_start" class="hasDatepicker" value="2018-11-01" />
            <label>End date</label>
            <input type="date" name="end" id="Date_end" class="hasDatepicker" value="2019-01-29" />
            <button type="submit" class="modalBtn text-light m-1 p-1 ">Between these dates</button>
        }
    </div>
</div>
<div class="row_d">
    @foreach (Days d in ViewBag.dage)
    {
        <div class="col_7 row text-capitalize card-header bg-transparent text-bold pb-0" style="curser:pointer;">
            <p class="text-center w-100">@d.dag</p>
        </div>

    }
    @foreach (CourseCalender course in ViewBag.TO)
    {
        @Html.Partial("_calender_teacher", course)
    }
</div>

ATTime/Views/TeacherView/student.cshtml
@using ATTime.Models
@{
    ViewBag.Title = "student";
    Layout = "~/Views/Shared/_Layout_Teacher_two.cshtml";
}

<div class="row att_row">
    <h2 class="mb-1 text-lg-left w-100">Students</h2>
    <br />
    @foreach (TeamStudent student in ViewBag.students)
    {
        @Html.Partial("_student_teacher", student)
    }
</div>